version: '2.1'

services:
  pyspark-app:
    container_name: pyspark-app
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../:/mounted-data
    depends_on:
      spark:
        condition: service_started
      spark-worker:
        condition: service_started

  spark:
    image: docker.io/bitnami/spark:3.4
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master --host spark --port 7077 --webui-port 8080
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '7077:7077'
      - '8080:8080'
    volumes:
      - ../:/mounted-data
  spark-worker:
    image: docker.io/bitnami/spark:3.4
    container_name: sprak-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark:7077
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ../:/mounted-data
    depends_on:
      spark:
       condition: service_started